apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowmint-postgres-pvc
  namespace: flowmint
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: linode-block-storage-retain
